### PR TITLE
Fix build on PHP 8.1 beta1

### PR DESCRIPTION
**Pull request by andypost**
Build fails  because 8.1 changed `PHP_ATOL()` https://github.com/php/php-src/commit/efbb2198d4e5a01167d1a8c2937b848f75ac4d19

### CODE REVIEW

**Comment by andypost** [comment]
```
/mnt/community/php8-pecl-yaml/src/yaml-2.2.1/detect.c: In function 'scalar_is_numeric':
/mnt/community/php8-pecl-yaml/src/yaml-2.2.1/detect.c:545:24: error: macro "ZEND_ATOL" passed 2 arguments, but takes just 1
  545 |    ZEND_ATOL(*lval, buf);
      |                        ^
In file included from /usr/include/php8/Zend/zend_range_check.h:22,
                 from /usr/include/php8/Zend/zend_portability.h:74,
                 from /usr/include/php8/Zend/zend_types.h:25,
                 from /usr/include/php8/Zend/zend.h:27,
                 from /usr/include/php8/main/php.h:31,
                 from /mnt/community/php8-pecl-yaml/src/yaml-2.2.1/php_yaml.h:46,
                 from /mnt/community/php8-pecl-yaml/src/yaml-2.2.1/detect.c:36:
/usr/include/php8/Zend/zend_long.h:76: note: macro "ZEND_ATOL" defined here
   76 | #  define ZEND_ATOL(s) atoll((s))
      | 
/mnt/community/php8-pecl-yaml/src/yaml-2.2.1/detect.c:545:4: error: 'ZEND_ATOL' undeclared (first use in this function); did you mean 'ZEND_AST_OR'?
  545 |    ZEND_ATOL(*lval, buf);
      |    ^~~~~~~~~
      |    ZEND_AST_OR
```

**Comment by andypost** [comment]
Getting one failed test
```
TEST 43/74 [tests/yaml_parse_file_002.phpt]
========DIFF========
001+ Deprecated: yaml_parse_file(): Passing null to parameter #1 ($filename) of type string is deprecated in /mnt/community/php8-pecl-yaml/src/yaml-2.2.1/tests/yaml_parse_file_002.php on line 4
002+ 
     Warning: yaml_parse_file(): %r(Filename|Path)%r cannot be empty in %s on line %d
     
     Warning: yaml_parse_file(): %r(Filename|Path)%r cannot be empty in %s on line %d
--
========DONE========
FAIL yaml_parse_file - error cases [tests/yaml_parse_file_002.phpt] 
```

**Comment by andypost** [comment]
Test relaxed in https://github.com/php/pecl-file_formats-yaml/pull/59

**Comment by mlocati** [comment]
Any ETA about a new yaml release on pecl?

**Comment by mlocati** [comment]
PHP 8.1RC2 is now available. It's time for a new release of yaml supporting PHP 8.1, isn't it?

**Comment by neclimdul** [comment]
Makes sense. Release is getting close ~~no~~ so, any chance of merging and releasing this?

**Comment by bd808** [comment]
Fixed by b35ef25b4b766c27b27b6293d3045e768e6ce677

**Comment by bd808** [comment]
Fixes included in https://pecl.php.net/package/yaml/2.2.2

**Comment by andrey-helldar** [comment]
dll for windows [not ready](https://pecl.php.net/package/yaml/2.2.2/windows) yet?

**Comment by KGB1st** [comment]
not yet
